apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: m324-project-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: m324-project
    namespace: verapas
